import { LivestreamBattle, Comment, Gift } from "@/types/livebattle";

export const mockLivestreamBattles: LivestreamBattle[] = [
  {
    id: "1",
    title: "Dance Battle Royale",
    status: "live",
    scheduledTime: Date.now() - 1800000,
    creator1: {
      id: "c1",
      username: "DanceQueen",
      avatar: "https://i.pravatar.cc/150?img=1",
      followers: 25600,
      brdTokens: 15400,
    },
    creator2: {
      id: "c2",
      username: "GrooveMaster",
      avatar: "https://i.pravatar.cc/150?img=2",
      followers: 18900,
      brdTokens: 12300,
    },
    viewCount: 4580,
    likes1: 1230,
    likes2: 986,
    votes1: 456,
    votes2: 389,
    gifts1: 234,
    gifts2: 178,
    totalPrize: 2500,
    thumbnailUrl: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=800&h=600&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  },
  {
    id: "2",
    title: "Beatbox Championship",
    status: "live",
    scheduledTime: Date.now() - 900000,
    creator1: {
      id: "c3",
      username: "BeatMaster",
      avatar: "https://i.pravatar.cc/150?img=3",
      followers: 32000,
      brdTokens: 21500,
    },
    creator2: {
      id: "c4",
      username: "RhythmKing",
      avatar: "https://i.pravatar.cc/150?img=4",
      followers: 29700,
      brdTokens: 19800,
    },
    viewCount: 6120,
    likes1: 2150,
    likes2: 1980,
    votes1: 645,
    votes2: 590,
    gifts1: 312,
    gifts2: 287,
    totalPrize: 3000,
    thumbnailUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=600&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  },
  {
    id: "3",
    title: "Rap Battle Finals",
    status: "scheduled",
    scheduledTime: Date.now() + 3600000,
    creator1: {
      id: "c5",
      username: "LyricMaster",
      avatar: "https://i.pravatar.cc/150?img=5",
      followers: 41200,
      brdTokens: 28700,
    },
    creator2: {
      id: "c6",
      username: "FlowGenius",
      avatar: "https://i.pravatar.cc/150?img=6",
      followers: 38900,
      brdTokens: 26500,
    },
    viewCount: 0,
    likes1: 0,
    likes2: 0,
    votes1: 0,
    votes2: 0,
    gifts1: 0,
    gifts2: 0,
    totalPrize: 5000,
    thumbnailUrl: "https://images.unsplash.com/photo-1470813740244-df37b8c1edcb?w=800&h=600&fit=crop",
  },
  {
    id: "4",
    title: "Singing Competition",
    status: "scheduled",
    scheduledTime: Date.now() + 7200000,
    creator1: {
      id: "c7",
      username: "VocalDiva",
      avatar: "https://i.pravatar.cc/150?img=7",
      followers: 35600,
      brdTokens: 24300,
    },
    creator2: {
      id: "c8",
      username: "MelodyMaster",
      avatar: "https://i.pravatar.cc/150?img=8",
      followers: 32400,
      brdTokens: 22100,
    },
    viewCount: 0,
    likes1: 0,
    likes2: 0,
    votes1: 0,
    votes2: 0,
    gifts1: 0,
    gifts2: 0,
    totalPrize: 4000,
    thumbnailUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop",
  },
  {
    id: "5",
    title: "Comedy Showdown",
    status: "ended",
    scheduledTime: Date.now() - 86400000,
    creator1: {
      id: "c9",
      username: "JokeMaster",
      avatar: "https://i.pravatar.cc/150?img=9",
      followers: 28900,
      brdTokens: 19200,
    },
    creator2: {
      id: "c10",
      username: "LaughKing",
      avatar: "https://i.pravatar.cc/150?img=10",
      followers: 26500,
      brdTokens: 17800,
    },
    viewCount: 8750,
    likes1: 3200,
    likes2: 2950,
    votes1: 1230,
    votes2: 980,
    gifts1: 456,
    gifts2: 389,
    totalPrize: 3500,
    thumbnailUrl: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&h=600&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    durationMinutes: 45,
  },
];

export const mockComments: Comment[] = [
  {
    id: "comment1",
    userId: "user1",
    username: "FanGirl123",
    avatar: "https://i.pravatar.cc/150?img=11",
    text: "DanceQueen is killing it! 🔥🔥🔥",
    timestamp: Date.now() - 60000,
  },
  {
    id: "comment2",
    userId: "user2",
    username: "MusicLover",
    avatar: "https://i.pravatar.cc/150?img=12",
    text: "Go GrooveMaster! You got this!",
    timestamp: Date.now() - 120000,
  },
  {
    id: "comment3",
    userId: "user3",
    username: "DanceLife",
    avatar: "https://i.pravatar.cc/150?img=13",
    text: "Both of them are amazing! Can't decide who to vote for 😍",
    timestamp: Date.now() - 180000,
  },
  {
    id: "comment4",
    userId: "user4",
    username: "BeatFan",
    avatar: "https://i.pravatar.cc/150?img=14",
    text: "Just sent 100 BRD tokens! Let's go!",
    timestamp: Date.now() - 240000,
  },
];

export const mockGifts: Gift[] = [
  {
    id: "gift1",
    name: "Rose",
    icon: "🌹",
    price: 50,
  },
  {
    id: "gift2",
    name: "Heart",
    icon: "❤️",
    price: 100,
  },
  {
    id: "gift3",
    name: "Fire",
    icon: "🔥",
    price: 200,
  },
  {
    id: "gift4",
    name: "Crown",
    icon: "👑",
    price: 500,
  },
  {
    id: "gift5",
    name: "Diamond",
    icon: "💎",
    price: 1000,
  },
];
